apiVersion: v1
kind: Service
metadata:
  name: codebreaker-server
  namespace: codebreaker
spec:
  type: ClusterIP
  selector:
    app: codebreaker-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
